// aflgrab.idl : IDL source for aflgrab.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (aflgrab.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
	[
		object,
		uuid(B2815247-4CD1-4367-9A9D-49059F75B184),
		dual,
		helpstring("IAffilGrabber Interface"),
		pointer_default(unique)
	]
	interface IAffilGrabber : IDispatch
	{
		[id(1), helpstring("method Validate")] HRESULT Validate([in] BSTR username, [in] BSTR password, [in] BSTR authurl, [out, retval] int * returnval);
		[propget, id(2), helpstring("property rawoutput")] HRESULT rawoutput([out, retval] BSTR *pVal);
	};

[
	uuid(9AF92F8F-ED84-4B58-95C0-5F079C3A369E),
	version(1.0),
	helpstring("aflgrab 1.0 Type Library")
]
library AFLGRABLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(A7BA1FF3-1374-4A3A-8CED-B00015FADAE2),
		helpstring("AffilGrabber Class")
	]
	coclass AffilGrabber
	{
		[default] interface IAffilGrabber;
	};
};
