<?php
  include_once("D:\server\db_connect.inc")
?>

<html>
<head>
<title>Untitled Document</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">

<style>
<!--
body { font-family: Arial, Helvetica, sans-serif; font-size: 12pt }
.heading { font-weight: bold font-size: 14 pt; padding-left: 25px; padding-top: 20px }
.text { }
-->
</style>


</head>

<body bgcolor="#FFFFFF">

<form method="get" action="report.phtml">

  <table width="600" border="0" cellspacing="1" cellpadding="1">
    <tr> 
      <td class=heading><font size=+1>Produce an Evaluation Report</font></td>
    </tr>
    <tr> 
      <td> 
        <table width="500" border="0" cellspacing="0" cellpadding="0" align="left">
          <tr> 
            <td width=100 valign="top" class=heading>Description</td>
            <td class=text>Here, you may produce 
              a report on the evaluations of a specific class, an entire department, 
              the whole school, or for a custom selection of classes and departments.</td>
          </tr>
          <tr> 
            <td width=100 valign="top" class=heading>Instructions</td>
            <td>To produce a report, 
              first select the schools, departments and/or classes that you wish 
              to include in the report. If you want to select multiple classes 
              and/or departments, hold down the CTRL key and click on all of your 
              selections. After making your selections, click &quot;Submit&quot; 
              on the bottom to produce the report for your selections. Click &quot;Reset 
              Selections&quot; to start over.</td>
          </tr>
        </table>
      </td>
    </tr>
    <tr align="left"> 
      <td> 
        <table width="600" border="0" cellspacing="0" cellpadding="0">
          <tr> 
            <td class=heading><input type=radio name=grouping value=schools>Include these schools in the report...</td>
          </tr>
          <tr> 
            <td align="left"><select name="schools[]" multiple size="2"><option value="FFSEAS" selected>Fu Foundation School of Engineering 
                      and Applied Science</option>
                    </select>
                  </td>
                </tr>
              </table>
            </td>
          </tr>
          <tr> 
            <td>&nbsp;</td>
          </tr>
          <tr> 
            <td><input type=radio name=grouping value=departments>Include these departments 
              in the report...</td>
          </tr>
          <tr> 
            <td> 
              <table width="600" border="0" cellspacing="0" cellpadding="0">
                <tr> 
                  <td width=10%>&nbsp;</td>
                  <td align="left"> 
                    <select name="departments[]" multiple size=5>                  
<?php
   $departments = mysql_query("SELECT deptid,deptname FROM deptinfo ORDER BY deptname");
   while($department=mysql_fetch_row($departments))
   {
     echo "<option VALUE=\"$department[0]\">$department[1]</option>\n";     
   }?>
                    </select>
                  </td>
                </tr>
              </table>
            </td>
          </tr>
          <tr> 
            <td>&nbsp;</td>
          </tr>
          <tr> 
            <td><input type=radio name=grouping value=classes>Include these classes 
              in the report...  </td>
          </tr>
          <tr> 
            <td> 
              <table width="600" border="0" cellspacing="0" cellpadding="0">
                <tr> 
                  <td width="10%">&nbsp;</td>
                  <td align="left"> 
                    <select name="classes[]" multiple size=15>
<?php
   $classes = mysql_query("SELECT classid FROM classinfo ORDER BY classid");
   while($claess=mysql_fetch_row($classes))
   {
       $courses = mysql_query("SELECT coursename FROM courseinfo WHERE courseid = '" . substr($claess[0],0,9) . "'");       $course = mysql_fetch_row($courses);
       echo "<option VALUE=\"$claess[0]\">$claess[0] - $course[0]</option>\n";
   }?>                  
                    </select>
                  </td>
                </tr>
              </table>
            </td>
          </tr>
          <tr> 
            <td>&nbsp;</td>
          </tr>
        </table>
      </td>
    </tr>
    <tr>
      <td>
        <table width="600" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td width="10%">&nbsp;</td>
            <td width=100> 
              <input type=submit name=submit value="Submit">
            </td>
            <td width=100>
              <input type="reset" name="Reset" value="Reset Selections">
            </td>
          </tr>
        </table>
      </td>
    </tr>
    <tr> 
      <td>&nbsp;</td>
    </tr>
  </table>

</form>

</body>
</html>
