<?

$WCES_CONFIG_PATH = '/wces/';
$WCES_CONFIG_MEDIA_PATH = "{$WCES_CONFIG_PATH}media/";
$WCES_CONFIG_HELP_PATH = "{$WCES_CONFIG_PATH}help.php";

$WCES_CONFIG_PAGE_INCLUDE = 'config/ColumbiaPage.inc';
$WCES_CONFIG_PAGE = 'ColumbiaPage';

$WCES_CONFIG_FACTORIES_INCLUDE = 'config/survey.inc';
$WCES_CONFIG_FACTORIES = 'survey_factories';

$WBES_LOGIN_INCLUDE = 'config/ColumbiaLogin.inc';
$WBES_LOGIN = 'ColumbiaLogin';
$WBES_LOGIN_URL = 'http://wces.russ.hn.org/wces/login/login.php/insecure';
$WBES_LOGIN_SURL = 'http://wces.russ.hn.org/wces/login/login.php';
$WBES_LOGIN_LOGOUT = "{$WCES_CONFIG_PATH}login/logout.php";
$WBES_LOGIN_PREFIX = 'login/';

$WBES_CONFIG_MEDIA_PATH = "{$WCES_CONFIG_PATH}media/";

?>