INSERT INTO categories (ordinal, name) VALUES (1, 'Communication');
INSERT INTO categories (ordinal, name) VALUES (2, 'Decision Making');
INSERT INTO categories (ordinal, name) VALUES (3, 'Collaboration');
INSERT INTO categories (ordinal, name) VALUES (4, 'Self-Management');
INSERT INTO questions (category_id, ordinal, name) VALUES (1, 1, 'Listens attentively to others without interrupting');
INSERT INTO questions (category_id, ordinal, name) VALUES (1, 2, 'Conveys interest in what others are saying');
INSERT INTO questions (category_id, ordinal, name) VALUES (1, 3, 'Provides others with constructive feedback');
INSERT INTO questions (category_id, ordinal, name) VALUES (1, 4, 'Restates what has been said to show understanding');
INSERT INTO questions (category_id, ordinal, name) VALUES (1, 5, 'Clarifies what others have said to ensure understanding');
INSERT INTO questions (category_id, ordinal, name) VALUES (1, 6, 'Articulates ideas clearly and concisely');
INSERT INTO questions (category_id, ordinal, name) VALUES (1, 7, 'Uses facts to get points across to other');
INSERT INTO questions (category_id, ordinal, name) VALUES (1, 8, 'Persuades others to adopt a particular point of view');
INSERT INTO questions (category_id, ordinal, name) VALUES (1, 9, 'Gives compelling reasons for ideas');
INSERT INTO questions (category_id, ordinal, name) VALUES (1, 10, 'Winds support from others');
INSERT INTO questions (category_id, ordinal, name) VALUES (2, 1, 'Analyses problems from different points of view');
INSERT INTO questions (category_id, ordinal, name) VALUES (2, 2, 'Anticipates problems and develops contingency plans');
INSERT INTO questions (category_id, ordinal, name) VALUES (2, 3, 'Recognizes interrelationships among problems and issues');
INSERT INTO questions (category_id, ordinal, name) VALUES (2, 4, 'Review solutions from opposing perspectives');
INSERT INTO questions (category_id, ordinal, name) VALUES (2, 5, 'Applies logic in solving problems');
INSERT INTO questions (category_id, ordinal, name) VALUES (2, 6, 'Challenges the way things are being done');
INSERT INTO questions (category_id, ordinal, name) VALUES (2, 7, 'Solicits new ideas from others');
INSERT INTO questions (category_id, ordinal, name) VALUES (2, 8, 'Generates new ideas');
INSERT INTO questions (category_id, ordinal, name) VALUES (2, 9, 'Accepts change');
INSERT INTO questions (category_id, ordinal, name) VALUES (2, 10, 'Suggests new approaches to solving problems');
INSERT INTO questions (category_id, ordinal, name) VALUES (2, 11, 'Offers solutions based on facts rather than "gut feel" or intuition');
INSERT INTO questions (category_id, ordinal, name) VALUES (2, 12, 'Discourages others from rushing to conclusions without facts');
INSERT INTO questions (category_id, ordinal, name) VALUES (2, 13, 'Organizes information into meaningful categories');
INSERT INTO questions (category_id, ordinal, name) VALUES (2, 14, 'Helps others to draw conclusions from the facts');
INSERT INTO questions (category_id, ordinal, name) VALUES (2, 15, 'Bring in information from "outside" sources to help make decisions');
INSERT INTO questions (category_id, ordinal, name) VALUES (3, 1, 'Acknowledges issues that the team needs to confront and resolve');
INSERT INTO questions (category_id, ordinal, name) VALUES (3, 2, 'Encourages ideas and opinions oven when they differ from his/her own');
INSERT INTO questions (category_id, ordinal, name) VALUES (3, 3, 'Works toward solutions and compromises that are acceptable to all');
INSERT INTO questions (category_id, ordinal, name) VALUES (3, 4, 'Helps reconcile differences of opinion');
INSERT INTO questions (category_id, ordinal, name) VALUES (3, 5, 'Accepts criticism openly and non-defensively');
INSERT INTO questions (category_id, ordinal, name) VALUES (3, 6, 'Shares credit for successes with others');
INSERT INTO questions (category_id, ordinal, name) VALUES (3, 7, 'Cooperates with others');
INSERT INTO questions (category_id, ordinal, name) VALUES (3, 8, 'Encourages participation from all involved');
INSERT INTO questions (category_id, ordinal, name) VALUES (3, 9, 'Shares information with others');
INSERT INTO questions (category_id, ordinal, name) VALUES (3, 10, 'Reinforces the contributions of others');
INSERT INTO questions (category_id, ordinal, name) VALUES (4, 1, 'Monitors progress to ensure that goals are being met');
INSERT INTO questions (category_id, ordinal, name) VALUES (4, 2, 'Create action plans and timetables for work session goals');
INSERT INTO questions (category_id, ordinal, name) VALUES (4, 3, 'Defines task priorities for work session goals');
INSERT INTO questions (category_id, ordinal, name) VALUES (4, 4, 'Ensures that goals are understood by all');
INSERT INTO questions (category_id, ordinal, name) VALUES (4, 5, 'Puts top priority on getting results');
INSERT INTO questions (category_id, ordinal, name) VALUES (4, 6, 'Stays focused on the task during meetings');
INSERT INTO questions (category_id, ordinal, name) VALUES (4, 7, 'Uses meeting time efficiently');
INSERT INTO questions (category_id, ordinal, name) VALUES (4, 8, 'Suggests ways to proceed during work sessions');
INSERT INTO questions (category_id, ordinal, name) VALUES (4, 9, 'Clarifies roles and responsibilities of others');
INSERT INTO questions (category_id, ordinal, name) VALUES (4, 10, 'Review progress throughout work sessions');
INSERT INTO questions (category_id, ordinal, name) VALUES (4, 11, 'Solicits input from all member');
INSERT INTO questions (category_id, ordinal, name) VALUES (4, 12, 'Encourages frequent polling among team members');
INSERT INTO questions (category_id, ordinal, name) VALUES (4, 13, 'Summarizes the team''s position on issues');
INSERT INTO questions (category_id, ordinal, name) VALUES (4, 14, 'Involves others in decisions that affect them');
INSERT INTO questions (category_id, ordinal, name) VALUES (4, 15, 'Encourages others to express their views even when they are contrary');
